import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    name: "Men Checked Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/kwtkxowe/shirt/c/u/n/xl-brd-white-p-v-creat",
    alt: "mens shirt",
    brand: "Roadster",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 30,
    size: "L",
    idealFor: "M",
    rating: 4.2,
  },
  {
    _id: uuid(),
    name: "Women Crop Top",
    img: "https://rukminim1.flixcart.com/image/880/1056/krf91u80/top/g/n/v/xs-",
    alt: "womens top",
    brand: "Forever 21",
    newPrice: 750,
    oldPrice: 1499,
    discount: 50,
    size: "XS",
    idealFor: "F",
    rating: 4.5,
  },
  {
    _id: uuid(),
    name: "Men Denim Jacket",
    img: "https://rukminim1.flixcart.com/image/880/1056/jacket-denim",
    alt: "mens denim jacket",
    brand: "Levis",
    newPrice: 3200,
    oldPrice: 4999,
    discount: 36,
    size: "M",
    idealFor: "M",
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: "Women Floral Dress",
    img: "https://rukminim1.flixcart.com/image/880/1056/dress-floral",
    alt: "womens floral dress",
    brand: "Zara",
    newPrice: 2100,
    oldPrice: 2999,
    discount: 30,
    size: "S",
    idealFor: "F",
    rating: 4.6,
  },
  {
    _id: uuid(),
    name: "Men Running Shoes",
    img: "https://rukminim1.flixcart.com/image/880/1056/shoes-running",
    alt: "mens running shoes",
    brand: "Nike",
    newPrice: 4500,
    oldPrice: 5999,
    discount: 25,
    size: "9",
    idealFor: "M",
    rating: 4.8,
  },
  {
    _id: uuid(),
    name: "Women Handbag",
    img: "https://rukminim1.flixcart.com/image/880/1056/handbag",
    alt: "womens handbag",
    brand: "Michael Kors",
    newPrice: 8500,
    oldPrice: 12000,
    discount: 29,
    size: "One Size",
    idealFor: "F",
    rating: 4.9,
  },
  {
    _id: uuid(),
    name: "Men Leather Belt",
    img: "https://rukminim1.flixcart.com/image/880/1056/belt-leather",
    alt: "mens leather belt",
    brand: "Allen Solly",
    newPrice: 1200,
    oldPrice: 1800,
    discount: 33,
    size: "Free",
    idealFor: "M",
    rating: 4.3,
  },
  {
    _id: uuid(),
    name: "Women Sneakers",
    img: "https://rukminim1.flixcart.com/image/880/1056/sneakers-women",
    alt: "womens sneakers",
    brand: "Puma",
    newPrice: 3200,
    oldPrice: 4500,
    discount: 28,
    size: "6",
    idealFor: "F",
    rating: 4.4,
  },
  {
    _id: uuid(),
    name: "Men Casual T-Shirt",
    img: "https://rukminim1.flixcart.com/image/880/1056/tshirt-casual",
    alt: "mens casual t-shirt",
    brand: "H&M",
    newPrice: 900,
    oldPrice: 1299,
    discount: 31,
    size: "XL",
    idealFor: "M",
    rating: 4.1,
  },
  {
    _id: uuid(),
    name: "Women Woolen Scarf",
    img: "https://rukminim1.flixcart.com/image/880/1056/scarf-woolen",
    alt: "womens woolen scarf",
    brand: "Mango",
    newPrice: 650,
    oldPrice: 999,
    discount: 35,
    size: "Free",
    idealFor: "F",
    rating: 4.0,
  },
];
